apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jpprajapati529/Business-Management-System.git
    targetRevision: release        # <--- Connects to the main branch
    path: k8s/dev              # <--- Uses the prod config folder
  destination:
    server: https://kubernetes.default.svc
    namespace: dev             # <--- Deploys to the prod namespace
  syncPolicy:
    automated:                  # Enable automatic synchronization
      prune: true
      selfHeal: true