apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-Deployment
  labels:
    app: bms-app
spec:
  selector:
    matchLabels:
      app: bms-app
  template:
    metadata:
      labels:
        app: bms-app
    spec:
      containers:
      - name: bms_container
        image: jaijp/bms:latest
        ports:
        - containerPort: 8098
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m" # 250 milliCPU = 0.25 CPU cores
          limits:
            memory: "512Mi"
            cpu: "500m"