apiVersion: v1
kind: Pod
metadata:
  name: bms-pod
  labels:
    app: bms-app
    tier: backend
spec:
  containers:
  - name: bms-container
    image: jaijp/bms:latest
    ports:
    - containerPort: 8097
    resources:             # Optional: Resource requests and limits for the container
      requests:
        memory: "64Mi"     # Minimum memory requested (e.g., 64 MiB)
        cpu: "100m"        # Minimum CPU requested (100 milliCPU = 0.1 CPU core)
      limits:
        memory: "128Mi"    # Maximum memory allowed (e.g., 128 MiB)
        cpu: "200m"
