spring.datasource.name=businessproject
spring.datasource.url=jdbc:postgresql://localhost:5432/businessproject
spring.datasource.password=root
spring.datasource.username=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8092

