name: CI/CD pipeline
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  build:
    runs-on: self-hosted
  
    steps:

    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker build and deploy
      env: 
        image: jaijp/bms

      run: |
  
        docker build -t image:latest .
        docker tag image image:latest
        docker push image:latest
        docker compose up -d
    
    - name: build maven
      run: mvn clean install

    - name: echo
      run: echo "build successfull"

    - name: kubectl setup
      uses: azure/setup-kubectl@v3

    - name: Kind setup
      uses: helm/kind-action@v1

    - name: deploy to k8s
      run: |
        kubectl apply -f app-service.yaml
        kubectl apply -f app-deployment.yaml
        kubectl apply -f postgres-service.yaml
        kubectl apply -f postgres-statefulset.yaml

    # - name: set up helm
    #   uses: azure/setup-helm@v3
    #   with:
    #     version: "latest"

    # - name: setup prometheus
    #   run: |
    #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    #     helm repo update

    # - name: install/upgrade kube-prometheus-stack
    #   run: |
    #     helm upgrade --install prometheus \
    #       prometheus-community/kube-prometheus-stack \
    #       --namespace monitoring \
    #       --create-namespace \
    #       --set prometheus.prometheusSpec.retention=7d \
    #       --set alertmanager.alertmanagerSpec.replicaCount=2 \
    #       --wait --timeout 5m

    # - name: list all statefulsets
    #   run: |
    #     kubectl -n monitoring get statefulsets

    # - name: wait for prom
    #   run: |
    #     kubectl -n monitoring rollout status statefulset/prometheus-prometheus-kube-prometheus-prometheus --timeout=2m
        
    # - name: Query Prometheus for ‘up’ metrics
    #   run: |
    #     echo "🔍 Querying Prometheus for targets status…"
    #     curl -s "http://localhost:9090/api/v1/query?query=up" | jq .
